spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root1607
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
  sql:
    init:
      platform: org.hibernate.dialect.MySQL57Dialect
server:
  port: 8585